_BASE_: "../Base-RCNN-FPN.yaml"
SEED: 3407
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATALOADER:
  NUM_WORKERS: 4